### ISSUE TITLE
Some packages archived with error

### ISSUE THREAD

**Issue by DOrlov77** [afbobak/nopar#28] opened 2015-05-10 16:14 UTC
For example:
```
d:\workspace>npm install --registry http://localhost:5984/ caniuse-db@1.0.30000161
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--registry" "http://localhost:5984/" "caniuse-db@1.0.30000161"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! shasum check failed for c:\Temp\npm-4928-dc9fb93a\localhost_5984\caniuse-db\-\caniuse-db-1.0.30000161.tgz
npm ERR! Expected: c5e03847e8b981d373d378e7bb51c89ebea1cd10
npm ERR! Actual:   67e2c642291c7f9c8717c5bec0193241fbf8ab37
npm ERR! From:     http://localhost:5984/caniuse-db/-/caniuse-db-1.0.30000161.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     d:\workspace\npm-debug.log

d:\workspace>
```

And cached ```caniuse-db-1.0.30000161.tgz``` is corruped.
Despite on that - the command
```npm install caniuse-db@1.0.30000161```
works well.
Fixed the issue manually by replacing the corruped file by valid one...

**Comment by afbobak** [comment] 2015-05-11 03:27
Can you reproduce this? If not, do you still have the nopar logfile/logging output? Looks like an intermittent network problem that nopar is not catching.

**Comment by glenjamin** [comment] 2015-05-11 06:21
I've seen this myself a few times, never managed to pin it down.

I tend to find that running install again gets the right checksum - so I suspect the response is sent before the download is complete.

**Comment by DOrlov77** [comment] 2015-05-11 12:16
The problem is here...
Where is the nopar log could be found?

___________
Best regards,
          Dmitry

**Comment by DOrlov77** [comment] 2015-05-12 12:09
Currently all new libs are affected. Couldn't continue to use ```nopar``` - in favor to [sinopia](https://github.com/rlidwka/sinopia). Sorry...

**Comment by glenjamin** [comment] 2015-05-20 20:32
I considered using sinopia, but while it's user management story is slightly better, it's GUI for seeing the state of the cache is missing many features of nopar.

I had a little look at what might be causing this.

https://github.com/afbobak/nopar/blob/develop/lib/attachment.js#L77 seems like a suspicious candidate.

**Comment by bobak** [comment] 2015-05-21 18:08
I can't remember anymore but it looks like I couldn't use "finish" because it didn't fire on node v0.8. As it's unlikely many people are using it anymore re-instating it again sounds good to me.

**Comment by bobak** [comment] 2015-06-06 02:41
Going to close this issue as I haven't seen it popup anymore. Please try v0.8.0.

**Closed by bobak** 2015-06-06 02:41 UTC
